### ISSUE TITLE
How to override default timeout

### ISSUE THREAD

**Issue by manjirinamjoshi** [kr1sp1n/node-vault#118]
Hello,

Would like to know how can we override the default timeout of 30 seconds ?

Thank you

Sincerely,
Manjiri

**Comment by kr1sp1n** [comment]
You could pass it as request options (https://github.com/request/request#requestoptions-callback):
```js
const options = {
  requestOptions: {
    timeout: 500, // in milliseconds
  },
};
vault.auths(options)
...
```
See https://github.com/kr1sp1n/node-vault/blob/master/example/auth.js for an example.
Let me know if it works. Thanks! 🙏
