### ISSUE TITLE
Namespace and mount point path support?

### ISSUE THREAD

**Issue by tylersmith34** [kr1sp1n/node-vault#123]
Does this library support defining the namespace and mount point path when reading from Vault?  I'm authenticating to the namespace and trying to read a value stored inside the namespace but am getting a 403.

The Token I passed to this library came from this command:
`vault login -method=ldap -namespace=<namespace> -path=<mpp> username=<username> password=<password>`

Using the CLI I can retrieve the value (I'm the namespace admin and have full access).

**Comment by DrakkenSaer** [comment]
Was this issue ever answered? All I see is a link to a ticket specifying how to add a namespace. How is a mount path added?
