### ISSUE TITLE
Error with creating AppRole

### ISSUE THREAD

**Issue by crivera** [kr1sp1n/node-vault#128]
Hi

I just downloaded the src and was trying to run the examples. After setting up vault with docker compose and initializing it (following your scripts) I tried to run the auth_approle script but got the following error:

`VAULT_TOKEN=s.FX3Rp3iVukpZhVYdC436wmpF VAULT_ADDR=http://localhost:8200 node example/auth_approle.js
  node-vault GET http://localhost:8200/v1/sys/auth +0ms
  node-vault 200 +26ms
  node-vault POST http://localhost:8200/v1/sys/auth/approle +2ms
  node-vault { mount_point: 'approle',
  node-vault   type: 'approle',
  node-vault   description: 'Approle auth' } +0ms
  node-vault 204 +9ms
Cannot convert undefined or null to object`

I traced it down to the extendOptions function line 180: 
`for (const key of Object.keys(reqSchema.properties)) {`

in the case of approle the reqSchema has not properties object. I think this has to do with the fact that in command.js the `addApproleRole` is defined wrong.

` addApproleRole: {
    method: 'POST',
    path: '/auth/{{mount_point}}{{^mount_point}}approle{{/mount_point}}/role/{{role_name}}',
    schema: {
      req: {
        bind_secret_id: {
          type: 'boolean',
        },
        bound_cidr_list: {
          type: 'string',
        },
        policies: {
          type: 'string',
        },
        secret_id_num_uses: {
          type: 'integer',
        },
        secret_id_ttl: {
          type: 'integer',
        },
        token_num_uses: {
          type: 'integer',
        },
        token_ttl: {
          type: 'integer',
        },
        token_max_ttl: {
          type: 'integer',
        },
        period: {
          type: 'integer',
        },
      },
    },
  },
`

the request object should be:

type: 'object',
properties: {
    ...
}

Let me know if this is true and i can create a PR

**Comment by crivera** [comment]
oh looks like 2 people have already created a PR

https://github.com/kr1sp1n/node-vault/pull/120

is this library not in dev anymore?

**Comment by kr1sp1n** [comment]
@crivera Thanks for reporting this issue. Fix is now published in v0.9.10. 🎉 This lib is still in active development but most of the times I'm not as fast as I wish 😬
