### ISSUE TITLE
gcpLogin type missing

### ISSUE THREAD

**Issue by leeuwd** [kr1sp1n/node-vault#147]
`gcpLogin(options?: Option): Promise<any>;` function is missing from https://github.com/kr1sp1n/node-vault/blob/master/index.d.ts

**Comment by mikeboan** [comment]
opened a PR to add this type. Meanwhile, this seems to be working for me:

1. Make your own node-vault.d.ts file somewhere in your app
```
import NodeVault from "node-vault";

declare module "node-vault" {
  // tslint:disable-next-line:class-name
  interface client {
    gcpLogin(options?: NodeVault.Option): Promise<any>;
  }
}
```

2. add that file/directory to tsconfig.json:
```
{
  "compilerOptions": {
    "typeRoots": ["relative/path/to/new/typedef/file", "node_modules/@types"]  
  }
}
```
