### ISSUE TITLE
trying to unseal vault .. gives error message "vault is sealed" ..

### ISSUE THREAD

**Issue by jmls** [kr1sp1n/node-vault#15]
Well, I'm trying to use the unseal() method , but when I do, I get the message

```
 { [Error: Vault is sealed] statusCode: 503, statusMessage: 'Service Unavailable' }
```

yes, well, I agree - that's why I am trying to *unseal* it ;)

**Comment by kr1sp1n** [comment]
@jmls: Can you please be more specific:

- how do you start the vault server?
- how is the config for the vault server?
- how looks your code exactly?

Thanks!

**Comment by jmls** [comment]
ya, my bad. code that is ;)
