### ISSUE TITLE
Version 0.9.14 breaks compatibility with Node.js 8

### ISSUE THREAD

**Issue by axiac** [kr1sp1n/node-vault#153]
Version `0.9.13` can be used with Node.js 8.
Version `0.9.14` adds `snyk` as a dependency and one of its dependencies require Node.js 10.

I suggest removing `snyk` from `0.9`, releasing the version that uses `snyk` as `0.10` and updating `README.md` to mention the Node.js compatibility of each version.

As of April 2020 I doubt version `0.9.13` can be used with Node.js 6 (`README.md` recommends using Node.js >= 6), not because of `node-vault` itself but because of its dependencies and their dependencies.

**Comment by kr1sp1n** [comment]
Thanks for reporting this issue. I removed snyk completely with version 0.9.16.
