### ISSUE TITLE
Promise support?

### ISSUE THREAD

**Issue by blimmer** [kr1sp1n/node-vault#16]
Is there any plan to support promises instead of callbacks for this project?

**Comment by kr1sp1n** [comment]
@blimmer I thought about it already and will support Promises in the near future.
But you could use bluebird's promisifyall feature to have Promises in node-vault out of the box.

See http://bluebirdjs.com/docs/api/promise.promisifyall.html

**Comment by blimmer** [comment]
I actually switched over to using the vaulted package which supports promises out of the box. I wonder if, with Promise support, these libraries will be similar enough to merge. I am using a very limited subset of functionality (connect / read), so please excuse me if the two projects are different is some way.

**Comment by aliatsis** [comment]
+1

**Comment by kr1sp1n** [comment]
Regarding Promises I opened PR #20. But it is still WIP.

**Comment by kr1sp1n** [comment]
@blimmer @aliatsis PR #20 with Promise support is now merged into master and tagged as v0.5.0

Have fun 🍸
