### ISSUE TITLE
ApiResponseError: getting 403 even though have right permissions in vault.

### ISSUE THREAD

**Issue by vishnudxb** [kr1sp1n/node-vault#166]
I am using approle login method and trying to fetch secrets using the below code:  I am getting a 403 error using the below code however I am able to fetch the secrets with the token its generated by using the vault cli. 

```
const {
  ROLE_ID,
  SECRET_ID,
  VAULT_ADDR,
  VAULT_PATH,
} = process.env;

var options = {
   apiVersion: 'v1',
   endpoint: VAULT_ADDR,
};

var vault = require("node-vault")(options);

vault.approleLogin({ role_id: ROLE_ID, secret_id: SECRET_ID }).then((login_result) => {
  var client_token = login_result.auth.client_token;
  console.log("Using client token to login " + client_token);

  vault.read(VAULT_PATH).then((read_result) => {
    console.log(read_result);
  }).catch(console.error);
}).catch(console.error);

```

The output / error I am getting is below:

```
ApiResponseError: 1 error occurred:
	* permission denied


    at handleVaultResponse (./node_modules/node-vault/src/index.js:58:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  response: { statusCode: 403, body: { errors: [Array] } }
}
```

**Comment by ajdani** [comment]
@vishnudxb Hi,
did you resolve this issue?

If yes, do you remember how? I'm facing the same currently.

**Comment by OxyTJ** [comment]
> @vishnudxb Hi, did you resolve this issue?
> 
> If yes, do you remember how? I'm facing the same currently.

Add me to the list of those having issues. Any resolution? Here's a link to a reddit post I created: https://www.reddit.com/r/hashicorp/comments/yxcayo/comment/iwr7t5x/?context=3
