### ISSUE TITLE
requiring coffee-script interpreter breaks source-map-support

### ISSUE THREAD

**Issue by doublerebel** [kr1sp1n/node-vault#17]
Hello,

I'm using **node-vault** as a dependency in a project.  Because requiring the **coffee-script** interpreter monkey-patches `Error.prepareStackTrace()`, any code that I have with `require "source-map-support/register"` early in the file is overwritten by any later call to `require "node-vault"`.

**Comment by kr1sp1n** [comment]
Thanks for your PR, but could you please check why it breaks the tests on TravisCI?

**Comment by doublerebel** [comment]
@kr1sp1n Sure thing.  Looks like I forgot to commit the test updates last night.  I've squashed and pushed those to the PR, all tests are again passing.
