### ISSUE TITLE
Back to Javascript?

### ISSUE THREAD

**Issue by kr1sp1n** [kr1sp1n/node-vault#19]
I want to refactor this package to use Javascript in favour of Coffeescript.
Hey folks, what you think?

**Comment by aliatsis** [comment]
+1

**Comment by kr1sp1n** [comment]
Ok, opened PR #20. But is still WIP.

**Comment by justechn** [comment]
Any idea when this will be merged?

**Comment by kr1sp1n** [comment]
PR #20 is now merged into master and tagged as v0.5.0
