### ISSUE TITLE
SSL options

### ISSUE THREAD

**Issue by crazed** [kr1sp1n/node-vault#22]
Currently if you use a self-signed certificate, I don't see an easy way to use this with node-vault. The only way seems to be:

```
var https = require('https');
https.globalAgent.options = {
    rejectUnauthorized: false,
    ca: <string of ca>,
};
```

The `Vault.prototype._handleCallback` function seems to mangle the original options passed into individual requests before passing on to the `request` module.

**Comment by BeneStem** [comment]
Got this error now too.
Would be great if we could get a fix soonish :P
If you want me to help I can make a PR to fix it...
Greetz
/ben

**Comment by kr1sp1n** [comment]
@crazed @BeneStem What about this example here: https://github.com/kr1sp1n/node-vault/blob/c81353ead66ffb5403dfaca70d125917f3c05695/example/pass_request_options.js

You can pass `agentOptions` to any request but would this solve the issue with the self-signed certs?

**Comment by BeneStem** [comment]
I haven't tried the new version yet.

With the old coffeescript non-promise version the request options where overwritten.
There is a bug that the options are set into options.json and then option.json is set to null.

I will try the new version in 2 weeks when I am back from vacation.

Is it released yet?

Thanks for your reply and the example :)

Greetz
/ben

**Comment by kr1sp1n** [comment]
@BeneStem Yes, it is released. Latest version is 0.5.1
Would love to hear if this fixed your issue.

**Comment by BeneStem** [comment]
Thanks! I think you can close the issue for now. When I try it on Saturday I might open a new one. But it looks like it should work fine ;)
