### ISSUE TITLE
Doesn't respect VAULT_SKIP_VERIFY flag

### ISSUE THREAD

**Issue by kjatti** [kr1sp1n/node-vault#27]
Vault has an standard environment variable VAULT_SKIP_VERIFY which the vault cli client uses to ignore SSL errors when connecting to a vault server which has a self-signed/invalid SSL certificate. Since node-vault reads some of the standard vault environment variables like VAULT_ADDR and VAULT_TOKEN, one would ideally expect it to support VAULT_SKIP_VERIFY flag as well.

**Comment by kr1sp1n** [comment]
@kjatti Sorry for the late reply 😞 
In the next time I will work on integrating all of the standard vault environment variables listed here:
https://www.vaultproject.io/docs/commands/environment.html

And I will start with your requested `VAULT_SKIP_VERIFY` 😉

**Comment by hharnisc** [comment]
@kjatti @kr1sp1n was able to work around this with setting env variable NODE_TLS_REJECT_UNAUTHORIZED=0

**Comment by kjatti** [comment]
I am currently using NODE_TLS_REJECT_UNAUTHORIZED set to 0 to work around the issue but just so you know it disables https cert validation across the board, this can possibly introduce a security hole. I think a better option would be to just set it on the http request (that way it's scoped to just that call).
See http://stackoverflow.com/questions/20433287/node-js-request-cert-has-expired#answer-29397100

**Comment by kr1sp1n** [comment]
@kjatti @hharnisc It's possible to pass request options to my vault lib, please see https://github.com/kr1sp1n/node-vault/blob/master/example/pass_request_options.js for an example. As long as I did not implement the global `VAULT_SKIP_VERIFY` you have to pass the options with every vault request. Will keep you in the loop and notify you when it's done, ok?
