### ISSUE TITLE
Token is not optional anymore.

### ISSUE THREAD

**Issue by marcoslopes** [kr1sp1n/node-vault#40]
Beforehand(0.4.5) token addition to the header [was conditional on it having a value](https://github.com/kr1sp1n/node-vault/blob/v0.4.5/src/node-vault.coffee#L103).

With commit https://github.com/kr1sp1n/node-vault/commit/1e8fcf3fdca7d6930eaf47cebac367257e76860b that stopped happening.

We need to be able to perform requests without a token, to authenticate yourself with other methods for example.

However the following error occurs when updating to the latest version and probably all versions where commit https://github.com/kr1sp1n/node-vault/commit/1e8fcf3fdca7d6930eaf47cebac367257e76860b lies in. 

```
< uncaughtException:  Error: "value" required in setHeader("X-Vault-Token", value)
<     at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:342:11)
<     at new ClientRequest (_http_client.js:85:14)
<     at Object.exports.request (http.js:31:10)
<     at Request.start (/Users/mlopes/workspace/expedia/ewe/applications/cloudtoolbox-web/node_modules/request/request.js:801:30)
<     at Request.write (/Users/mlopes/workspace/expedia/ewe/applications/cloudtoolbox-web/node_modules/request/request.js:1466:28)
<     at end (/Users/mlopes/workspace/expedia/ewe/applications/cloudtoolbox-web/node_modules/request/request.js:528:18)
<     at /Users/mlopes/workspace/expedia/ewe/applications/cloudtoolbox-web/node_modules/request/request.js:552:9
<     at _combinedTickCallback (internal/process/next_tick.js:67:7)
<     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Thank you very much in advance =]

**Comment by kr1sp1n** [comment]
@marcoslopes OK, will have a look at it asap...thanx for finding this issue 👍

**Comment by marcoslopes** [comment]
@kr1sp1n no, thank you for the prompt reply! =]

**Comment by kr1sp1n** [comment]
@marcoslopes Should be fixed now since version 0.5.5
Please verify! Thanks 👍

**Comment by marcoslopes** [comment]
@kr1sp1n yeah it works like a charm! thanks heaps for that! 👍

**Comment by dishcandanty** [comment]
This broken again? Using userpass authentication. Which seems to succeed, but further calls fail.

node-vault@^0.5.6
```
Unhandled rejection Error: missing client token
    at handleVaultResponse (node_modules/node-vault/dist/index.js:36:19)
    at tryCatcher (node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by kr1sp1n** [comment]
@dishcandanty Will have a look asap.

**Comment by kr1sp1n** [comment]
@dishcandanty I tested it and improved the examples in the `develop` branch.
Here is how it works for me now:
1. Start vault
```docker-compose up --force-recreate vault```
1. Initialize vault and copy `root_token` from the response
```node example/init.js```
1. Set env var `VAULT_TOKEN`
```export VAULT_TOKEN=[root_token]```
1. Add policy `mypolicy`
```node example/addPolicy.js```
1. Enable userpass auth
```node example/enableAuth_userpass.js```
1. Login via userpass auth
```node example/userpassLogin.js```

It is required that you set `vault.token` to the `client_token` value from the login response.
That is at the moment far from perfect. Would be better to set the token automatically after any login strategy (e.g. github etc.).

**Comment by kr1sp1n** [comment]
Ok, will close this issue for now.
