### ISSUE TITLE
CI: docker-compose always exits with exit doe 0

### ISSUE THREAD

**Issue by fearphage** [kr1sp1n/node-vault#47]
It doesn't matter whether tests fail or not, `docker-compose` exits with exit code 0.

docker/compose#3379

I tried fixing it with no luck:

* added `tty: true` -- tests hang when done
* changed `cmd` to `sh -c 'npm test; exit $?` -- `docker-compose` still swallowed it

**Comment by kr1sp1n** [comment]
Ok, now I use just `docker run` to spawn a vault dev server and do a `npm run coverage`. 
Works fine! @fearphage Thanks for reporting this issue 🙏
