### ISSUE TITLE
Errors include request headers

### ISSUE THREAD

**Issue by sjparkinson** [kr1sp1n/node-vault#50]
On an error with the response we are dumping the [response object as part of the error](https://github.com/kr1sp1n/node-vault/blob/master/src/index.js#L40).

This often leads to the request headers being printed to console, or worse logged in whatever system people use with a potential valid token in the message.

**Comment by kr1sp1n** [comment]
So would be better to leave out the response object, right?

**Comment by sjparkinson** [comment]
Yep I think so, for a library like this always good to be sure of what is
in any logged messages.

**Comment by sjparkinson** [comment]
Thanks for merging that @kr1sp1n! Would you mind cutting a new release too?

**Comment by kr1sp1n** [comment]
Will realease a new version today!

**Comment by kr1sp1n** [comment]
Released v0.5.7 https://www.npmjs.com/package/node-vault

**Comment by sjparkinson** [comment]
Thank you!

**Comment by trevorr** [comment]
This is a regression of intentionally added functionality. How can callers handle errors like 404?

**Comment by DaniGuardiola** [comment]
@kr1sp1n we should try to finish the 1.0 version and push it live so that we don't duplicate efforts
