### ISSUE TITLE
Support for approle route?

### ISSUE THREAD

**Issue by uLan08** [kr1sp1n/node-vault#53]
As the title says, is there support for `auth/approle`? I have checked through the [features](https://github.com/kr1sp1n/node-vault/blob/master/features.md) page and it seems only `auth/token` is present.

**Comment by kr1sp1n** [comment]
It should not a big deal to add it. Will open PR for that!

**Comment by uLan08** [comment]
I'll try to add an implementation for that, no promises though :)

**Comment by uLan08** [comment]
Merged in #55
