### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by kevinSuttle** [kr1sp1n/node-vault#6]
I'm wondering if there are docs to 
- [ ] explain real-world usage scenarios for on-boarding and authenticating new teammates, as well as that if that process is automatable
- [ ] whether or not this is in memory or connecting to a hosted Vault backend, along with tradeoffs of each

**Comment by kr1sp1n** [comment]
@kevinSuttle you can find an example to use github as an auth backend here: https://github.com/kr1sp1n/node-vault/blob/master/example/auth_github.coffee
But nevertheless you need a hosted Vault backend of course. I will try to add a short tutorial how to do that on a local machine first. Is that ok for you?

**Comment by kevinSuttle** [comment]
Sounds like a solid start. Thanks!

**Comment by kr1sp1n** [comment]
@kevinSuttle So I updated the [Examples section][examples] in the `README.md` how to set up a test environment via docker. Just follow the instructions and then you should be able to run all the examples.
Please give feedback if it works for you.

[examples]: https://github.com/kr1sp1n/node-vault/blob/master/README.md#examples

**Comment by kevinSuttle** [comment]
@kr1sp1n Thanks! I'll give it a go, and report back.
