### ISSUE TITLE
Using native promises

### ISSUE THREAD

**Issue by firefoxNX** [kr1sp1n/node-vault#60]
Can bluebird dependency be removed and use native promise instead? I tried to set promise in config but bluebird is still getting installed.

**Comment by firefoxNX** [comment]
@kr1sp1n - can you reply? I have the code ready and can send PR.

**Comment by kr1sp1n** [comment]
@firefoxNX Please send your PR.

**Comment by firefoxNX** [comment]
See https://github.com/kr1sp1n/node-vault/pull/62

**Comment by firefoxNX** [comment]
@kr1sp1n please review. Thanks.

**Comment by kr1sp1n** [comment]
Thanks 🙏
