### ISSUE TITLE
Split node-vault in different npm packages

### ISSUE THREAD

**Issue by kr1sp1n** [kr1sp1n/node-vault#75]
My idea is to split this library in different npm packages because the functionality of vault is growing so fast. We could have a basic client for system backend and then extended clients for secret backends, auth backends and plugin backends as well. I would love to keep the repo and manage the publishing of the npm packages with a tool like lerna (https://github.com/lerna/lerna). WDYT?

**Comment by DaniGuardiola** [comment]
@kr1sp1n I would close this because of the reasons I wrote in [this issue comment](https://github.com/kr1sp1n/node-vault/issues/76#issuecomment-355869048)

**Comment by DaniGuardiola** [comment]
Closing because of the reasons mentioned [here](https://github.com/kr1sp1n/node-vault/issues/76#issuecomment-355869048)
