### ISSUE TITLE
Unchecked debug logging can cause process to exit

### ISSUE THREAD

**Issue by davidcl64** [kr1sp1n/node-vault#8]
On line 135 (https://github.com/kr1sp1n/node-vault/blob/master/node-vault.coffee#L135)

    debug err if err
    debug "RES #{res.statusCode}"

If there is an error, res is likely undefined.  Logging the next line will throw an exception.

Could be changed to either return early or:

    debug err if err
    debug "RES #{res?.statusCode}"

**Comment by kr1sp1n** [comment]
@davidcl64 Thanks for you hint ;) Is now fixed since v0.3.1
